#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd.

# script should only display:

#    username
#    user id
#    Home directory path for the user

FILENAME="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -f 1,3,6 -d ':'  
done < $FILENAME
