#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

FILENAME="/etc/passwd"

while IFS=: read -r USERNAME PASSWORD USER_ID GROUP_ID USER_INFO HOME_DIR COMMAND
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIR and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_INFO"
done < $FILENAME
